import FWCore.ParameterSet.Types as CfgTypes
import FWCore.ParameterSet.Config as cms



plots_jetsBasic = cms.VPSet(

    cms.PSet(
    skip      = cms.bool(False),
    xLow      = cms.double(0),
    xHigh     = cms.double(10),
    nBins     = cms.int32(10),
    variable  = cms.string("numJets30"),
    xTitle    = cms.string("jet mult p_{T}>30 GeV"),
    yTitle    = cms.string("Events"),
    histoName = cms.string("numJet30"),
    cut       = cms.string(""),
    logy      = cms.int32(1),
    ),

    cms.PSet(
    skip      = cms.bool(False),
    xLow      = cms.double(0),
    xHigh     = cms.double(10),
    nBins     = cms.int32(10),
    variable  = cms.string("numJets30bTag"),
    xTitle    = cms.string("b-jet mult"),
    yTitle    = cms.string("Events"),
    histoName = cms.string("numBJet30"),
    cut       = cms.string(""),
    logy      = cms.int32(1),
    ),

    cms.PSet(
    skip      = cms.bool(False),
    xLow      = cms.double(0),
    xHigh     = cms.double(1.1),
    nBins     = cms.int32(22),
    variable  = cms.string("csv1"),
    xTitle    = cms.string("CSV jet 1"),
    yTitle    = cms.string("Events"),
    histoName = cms.string("csv1"),
    cut       = cms.string(""),
    logy      = cms.int32(0),
    ),

    cms.PSet(
    skip      = cms.bool(False),
    xLow      = cms.double(0),
    xHigh     = cms.double(1.1),
    nBins     = cms.int32(22),
    variable  = cms.string("csv2"),
    xTitle    = cms.string("CSV jet 2"),
    yTitle    = cms.string("Events"),
    histoName = cms.string("csv2"),
    cut       = cms.string(""),
    logy      = cms.int32(0),
    ),

    cms.PSet(
    skip      = cms.bool(False),
    xLow      = cms.double(0),
    xHigh     = cms.double(1.1),
    nBins     = cms.int32(22),
    variable  = cms.string("csv3"),
    xTitle    = cms.string("CSV jet 3"),
    yTitle    = cms.string("Events"),
    histoName = cms.string("csv3"),
    cut       = cms.string(""),
    logy      = cms.int32(0),
    ),

    cms.PSet(
    skip      = cms.bool(False),
    xLow      = cms.double(0),
    xHigh     = cms.double(1.1),
    nBins     = cms.int32(22),
    variable  = cms.string("csv4"),
    xTitle    = cms.string("CSV jet 4"),
    yTitle    = cms.string("Events"),
    histoName = cms.string("csv4"),
    cut       = cms.string(""),
    logy      = cms.int32(0),
    ),

    cms.PSet(
    skip      = cms.bool(False),
    xLow      = cms.double(-5.5),
    xHigh     = cms.double(5.5),
    nBins     = cms.int32(22),
    variable  = cms.string("eta1"),
    xTitle    = cms.string("#eta jet 1"),
    yTitle    = cms.string("Events"),
    histoName = cms.string("eta1"),
    cut       = cms.string(""),
    logy      = cms.int32(0),
    ),

    cms.PSet(
    skip      = cms.bool(False),
    xLow      = cms.double(-5.5),
    xHigh     = cms.double(5.5),
    nBins     = cms.int32(22),
    variable  = cms.string("eta2"),
    xTitle    = cms.string("#eta jet 2"),
    yTitle    = cms.string("Events"),
    histoName = cms.string("eta2"),
    cut       = cms.string(""),
    logy      = cms.int32(0),
    ),

    cms.PSet(
    skip      = cms.bool(False),
    xLow      = cms.double(-5.5),
    xHigh     = cms.double(5.5),
    nBins     = cms.int32(22),
    variable  = cms.string("eta3"),
    xTitle    = cms.string("#eta jet 3"),
    yTitle    = cms.string("Events"),
    histoName = cms.string("eta3"),
    cut       = cms.string(""),
    logy      = cms.int32(0),
    ),

    cms.PSet(
    skip      = cms.bool(False),
    xLow      = cms.double(-5.5),
    xHigh     = cms.double(5.5),
    nBins     = cms.int32(22),
    variable  = cms.string("eta4"),
    xTitle    = cms.string("#eta jet 4"),
    yTitle    = cms.string("Events"),
    histoName = cms.string("eta4"),
    cut       = cms.string(""),
    logy      = cms.int32(0),
    ),

    cms.PSet(
    skip      = cms.bool(False),
    xLow      = cms.double(30),
    xHigh     = cms.double(390),
    nBins     = cms.int32(30),
    variable  = cms.string("pt1"),
    xTitle    = cms.string("p_{T} jet 1"),
    yTitle    = cms.string("Events"),
    histoName = cms.string("pt1"),
    cut       = cms.string(""),
    logy      = cms.int32(1),
    ),

    cms.PSet(
    skip      = cms.bool(False),
    xLow      = cms.double(30),
    xHigh     = cms.double(390),
    nBins     = cms.int32(30),
    variable  = cms.string("pt2"),
    xTitle    = cms.string("p_{T} jet 2"),
    yTitle    = cms.string("Events"),
    histoName = cms.string("pt2"),
    cut       = cms.string(""),
    logy      = cms.int32(1),
    ),

    cms.PSet(
    skip      = cms.bool(False),
    xLow      = cms.double(30),
    xHigh     = cms.double(390),
    nBins     = cms.int32(30),
    variable  = cms.string("pt3"),
    xTitle    = cms.string("p_{T} jet 3"),
    yTitle    = cms.string("Events"),
    histoName = cms.string("pt3"),
    cut       = cms.string(""),
    logy      = cms.int32(1),
    ),

    cms.PSet(
    skip      = cms.bool(False),
    xLow      = cms.double(30),
    xHigh     = cms.double(390),
    nBins     = cms.int32(30),
    variable  = cms.string("pt4"),
    xTitle    = cms.string("p_{T} jet 4"),
    yTitle    = cms.string("Events"),
    histoName = cms.string("pt4"),
    cut       = cms.string(""),
    logy      = cms.int32(1),
    ),

    )
